config/routes.rb
Relect::Application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'users/confirmations', :passwords => 'users/passwords',
                                       :registrations => 'users/registrations', :sessions => 'users/sessions'
                                     }

  resources :elections do
    resources :races

    member do
      get :vote
      put :cast_votes
      patch :cast_votes
      get :results
    end
  end
  
  resources :candidates
  resources :users

  root to: 'elections#index'
end

app/models/election.rb
class Election < ActiveRecord::Base
  attr_accessible :name, :races_attributes, :locked

  has_many :races

  accepts_nested_attributes_for :races

  validates_presence_of :name

  def results
    {}.tap do |results|
      races.each do |race|
        results[race.position] = race.results
      end
    end
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  load_and_authorize_resource

  before_filter :find_election, except: [:index, :new, :create]
  before_filter :check_locked, only: [:vote, :cast_votes]

  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elections }
    end
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/new
  # GET /elections/new.json
  def new
    @election = Election.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(params[:election])

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render json: @election, status: :created, location: @election }
      else
        format.html { render action: "new" }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elections/1
  # PUT /elections/1.json
  def update
    respond_to do |format|
      if @election.update_attributes(params[:election])
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy

    respond_to do |format|
      format.html { redirect_to elections_url }
      format.json { head :no_content }
    end
  end

  def vote
    if current_user.has_voted_in_election?(@election)
      flash[:error] = "Sorry, you have already voted in this election"
      redirect_to root_path
    end
  end

  def cast_votes
    if current_user.has_voted_in_election?(@election)
      flash[:error] = "Sorry, you have already voted in this election"
      redirect_to root_path and return
    end

    respond_to do |format|
      if @election.update_attributes(params[:election])
        format.html { redirect_to elections_path, notice: "Your vote has been cast for election: #{@election.name}" }
        format.json { head :no_content }
      else
        format.html { render action: :vote }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def results
    @election = Election.find(params[:id])
    @results = @election.results
  end

  private

  def find_election
    @election = Election.find(params[:id])
  end

  def check_locked
    if @election.locked?
      flash[:error] = 'Sorry, voting is closed for this election.'
      redirect_to root_path
      false
    end
  end
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/_form.html.erb
<%= form_for @election, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :model => @election } %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :locked, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :locked %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                elections_path, :class => 'btn' %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<%- model_class = Election -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/elections/index.html.erb
<%- model_class = Election -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <tbody>
    <% @elections.sort_by(&:name).each do |election| %>
      <tr>
        <td>
          <%= link_to_if can?(:edit, election), election.name, election_path(election) %>
        </td>
        <td>
          <% election.races.each do |race| %>
            <%= link_to_if can?(:edit, election), race.position, election_race_path(election, race) %><br/>
          <% end -%>
          <%= link_to 'Add Race', new_election_race_path(election) if can?(:edit, election) %>
        </td>
        <td>
          <% unless election.locked? %>
            <%= link_to 'VOTE',
                        vote_election_path(election), :class => 'btn btn-primary' %>
          <% end %>
          <%= link_to 'Results',
                      results_election_path(election), :class => 'btn btn-success' %>
          <% if can? :edit, Election %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_election_path(election), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        election_path(election),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Election %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_election_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/elections/new.html.erb
<%- model_class = Election -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'New %{model}', :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/elections/results.html.erb
<h1>Results</h1>
<% @results.to_a.sort_by { |result| result[0] }.each do |race, results| %>
  <h2><%= race %></h2>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Candidate</th>
        <th>Vote Total</th>
      </tr>
    </thead>
    <tbody>
      <% results[:results].each_with_index do |row, index| %>
        <tr class="<%= 'success' if index == 0 %>">
          <td><%= index + 1 %></td>
          <td><%= row[0] %></td>
          <td><%= row[1] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/elections/show.html.erb
<%- model_class = Election -%>
<div class="page-header">
  <h1><%= @election.name %> <%= '(Locked)' if @election.locked? %></h1>
</div>

<dl class="dl-horizontal">
  <% @election.races.each do |race| %>
    <dt><strong>Race:</strong></dt>
    <dd><%= link_to race.position, election_race_path(@election, race) %></dd>
  <% end -%>
  
  <dt/><dd><%= link_to 'Add Race', new_election_race_path(@election) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              elections_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_election_path(@election), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              election_path(@election),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elections/vote.html.erb
<%= form_for @election, :url => cast_votes_election_path(@election), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :model => @election } %>
  <%= f.fields_for :races do |race_form| %>
    <h2><%= race_form.object.position %></h2>
    <% (1..3).each do |i| %>
      <%= race_form.fields_for 'votes_attributes[]', Vote.new do |vote| %>
        <%= vote.hidden_field :rank, :value => i %>
        <%= vote.hidden_field :user_id, :value => current_user.id %>
        <div class="control-group">
          <%= vote.label :candidate_id, "#{i.ordinalize} Choice Candidate", :class => 'control-label' %>
          <div class="controls">
            <%= vote.select :candidate_id, race_form.object.candidates.order(:name).map{|candidate| [candidate.name, candidate.id]}, :include_blank => true %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="form-actions">
    <%= f.submit 'Cast Vote', :class => 'btn btn-primary',
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                elections_path, :class => 'btn' %>
  </div>
<% end %>