config/routes.rb
Relect::Application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'users/confirmations', :passwords => 'users/passwords',
                                       :registrations => 'users/registrations', :sessions => 'users/sessions'
                                     }

  resources :elections do
    resources :races

    member do
      get :vote
      put :cast_votes
      patch :cast_votes
      get :results
    end
  end
  
  resources :candidates
  resources :users

  root to: 'elections#index'
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :name
  
  has_many :race_candidates
  has_many :races, :through => :race_candidates
  
  validates :name, :presence => true, :uniqueness => true

  accepts_nested_attributes_for :race_candidates
  accepts_nested_attributes_for :races
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  load_and_authorize_resource

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for @candidate, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :model => @candidate } %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                candidates_path, :class => 'btn' %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/index.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <% if can? :edit, Candidate %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to_if can?(:edit, candidate), candidate.name, candidate_path(candidate) %></td>
        <% if can? :edit, Candidate %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_candidate_path(candidate), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        candidate_path(candidate),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Candidate %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_candidate_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/candidates/new.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'New %{model}', :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/show.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @candidate.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              candidates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_candidate_path(@candidate), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              candidate_path(@candidate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>