config/routes.rb
Relect::Application.routes.draw do
  devise_for :users, :controllers => { :confirmations => 'users/confirmations', :passwords => 'users/passwords',
                                       :registrations => 'users/registrations', :sessions => 'users/sessions'
                                     }

  resources :elections do
    resources :races

    member do
      get :vote
      put :cast_votes
      patch :cast_votes
      get :results
    end
  end
  
  resources :candidates
  resources :users

  root to: 'elections#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Relect" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= yield :head %>
  </head>
  <body>
    <div class="wrapper">
      <div class="navbar navbar-fluid-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <% if user_signed_in? %>
              <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
            <% end %>
            <a class="brand" href="#">rElect</a>
            <% if user_signed_in? %>
              <div class="container-fluid nav-collapse">
                <ul class="nav">
                  <li><%= link_to "Elections", elections_path %></li>
                  <li><%= link_to "Candidates", candidates_path %></li>
                  <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </div>
              <!--/.nav-collapse -->
            <% end %>
          </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span9">
            <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">x</a>
                <%= msg %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div><!--/row-->

      </div> <!-- /container -->
      <div class="push"></div>
    </div>
    <div class="footer navbar-inner">
      <br/>
      <p>&copy; Jon Kessler 2013</p>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
  </body>
</html>